### ISSUE TITLE
1.0.1 No source code packaged

### ISSUE THREAD

**Issue by ckychris** [dipunm/use-focus-visible#15]
Version 1.0.1 does not contain any source code. 
@dipunm Might want to take a look at those dependent bot merges.

**Comment by dipunm** [comment]
@ckychris Please try now, v 1.0.2
I tested myself, but will wait for confirmation before closing this issue.

Thanks for the report.

**Comment by ckychris** [comment]
Hi Dipun,

Thank you for the quick follow up. Really appreciate it.

I can verified that it’s working well.

Kind regards,
Chris
